### ISSUE TITLE
OSError on Running complex_emulator.py with snes9x.so

### ISSUE THREAD

**Issue by varun27wahi** [lifning/python-retro#22]
Hi,

When trying to run the complex_emulator.py script in examples, I get the following error:

`Could not load variadic log wrapper module: OSError('/home/demonz/python-retro/c_ext/log_wrapper.c: invalid ELF header',)
retro_environment not implemented: ['SET_SUBSYSTEM_INFO']
retro_environment not implemented: 52
retro_environment not implemented: ['SET_CONTROLLER_INFO']
environment: could not set logging interface because C wrapper not loaded.
retro_environment not implemented: ['SET_SUPPORT_ACHIEVEMENTS']
retro_environment not implemented: ['SET_PERFORMANCE_LEVEL']
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
retro_environment not implemented: ['SET_INPUT_DESCRIPTORS']
Segmentation fault (core dumped)`

Please let me know how to resolve the issue, or replicate your system environment in order for it to run.

Thanks

**Comment by vivlim** [comment]
What core are you trying to use this with? It might help to build the core yourself with debug symbols and attach a debugger to it to see what’s wrong, we’ve only run this with a small number of cores

**Comment by lifning** [comment]
a fair few of the libretro cores out there assume the full featureset of retroarch and crash horribly if it's not present, even when they should be querying for environment capabilities and degrading gracefully.

it may help if you are able to build the native "variadic log wrapper module" helper lib alluded to at the beginning of this output - whatever core you're using might be able to give you some hints as to what it's trying to do before it crashes.

**Comment by varun27wahi** [comment]
Thanks! I'll try it out and get back if there's still an issue.
