### ISSUE TITLE
Could not load variadic log wrapper module

### ISSUE THREAD

**Issue by Jourdelune** [lifning/python-retro#23]
Hi, I have an error:
`Could not load variadic log wrapper module: OSError('/home/pi/Programmation/test/RetroArchPythonAPI/python-retro/c_ext/log_wrapper.so: cannot open shared object file: No such file or directory')`
Its possible to explain why I have this error?

**Comment by vivlim** [comment]
Which core are you trying to use?
#22 may have been similar.
