### ISSUE TITLE
sound is awful

### ISSUE THREAD

**Issue by lifning** [lifning/python-retro#3]

**Comment by lifning** [comment]
should probably take a look at how RetroArch implements it... we may need to make a native module to handle it if there's no good audio system for Python that can deal with it appropriately.

**Comment by vivlim** [comment]
maybe disable sound by default till then? 

it'd be nice to have a rudimentary ui to control the emulator and that may be a good candidate for a knob

**Comment by lifning** [comment]
disabled the callback in sync-or-sim for now

**Comment by lifning** [comment]
https://github.com/lifning/python-retro/pull/7
